### PR TITLE
Remove vagrant ssh hack

### PR DESCRIPTION
**Pull request by ncoghlan**

### CODE REVIEW

**Comment by shaded-enmity** [comment]
What do you think about generating a key pair for testing and checking that in the repo? I'm a bit worried about having to juggle with local users keys (especially in port-forwarded scenarios).

**Comment by ncoghlan** [comment]
Yeah, I think that will be better, especially as it avoids a few other problems:

- user may not have an RSA keypair
- user may have a passphrase on their RSA key
- user may not have started ssh-agent
- giving sudo processes access to the user's ssh-agent

If we add a top level "test_config" directory, put a pregenerated key there, and configure the Ansible roles for both the demo and integration test VMs to load it, we eliminate a whole host of potential failure modes.

**Comment by shaded-enmity** [comment]
LGTM, I'm going to create an issue about the `test_config` TLD and using a "skeleton key" in all our Ansible playbooks.

**Comment by shaded-enmity** [comment]
Aha, sloppy me, didn't notice the linked issue which already mentions the skeleton key, never mind :)

**Pull request merged**
