### PR TITLE
TRELLO-124: rename LeApp entry in Cockpit menu

### PR DESCRIPTION
**Pull request by vmindru**

### CODE REVIEW

**Comment by ncoghlan** [comment]
This will also require an update to the plugin tests to select the new name from the Cockpit nav menu.

**Comment by vmindru** [comment]
Jenkins: ok to test

**Comment by vmindru** [comment]
Jenkins: ok to test

**Comment by vmindru** [comment]
Jenkins: ok to test

**Comment by vmindru** [comment]
Jenkins: ok to test

**Comment by vmindru** [comment]
Jenkins: ok to test

**Comment by vmindru** [comment]
@ncoghlan @vinzenz @shaded-enmity @GAZDOWN @JacobCZ @mfranczy  - needs  review, merge once done.

**Comment by vmindru** [comment]
squashed the commits, CI is ok https://ci.centos.org/job/leapp-integration-tests/272/

**Pull request merged**
