### PR TITLE
Make ui user friendly

### PR DESCRIPTION
**Pull request by mfranczy**
This PR contains:
- Simplify the information displayed in Cockpit
- Remove the "reprovision" button
- Centralized migration button

### CODE REVIEW

**Comment by mfranczy** [comment]
How UI looks now:
screenshot from 2017-04-20 14-11-03

@shaded-enmity gave me the idea to keep hostname and ip in both tables instead of "Each source/target machine in the list contains just simple ID the admin will understand - either a hostname (if available) or IP". I agree it's better and readable for admin.

**Comment by shaded-enmity** [comment]
Looks amazing @mfranczy ! Would it be possible to vertically align the `>>` symbol with the table headers, I think it'll look better.

**Comment by mfranczy** [comment]
yes, you're right, it looks better
screenshot from 2017-04-20 15-07-04

**Comment by shaded-enmity** [comment]
Great, thanks! 🎉 Merging

**Pull request merged**
