### PR TITLE
Remove pipenv patches since delegator.py is now fixed

### PR DESCRIPTION
**Pull request by shaded-enmity**
While the PRs have already been merged we're waiting for new release in PyPI, hence the WIP flag.

### CODE REVIEW

**Comment by shaded-enmity** [comment]
@ncoghlan Good point, will regenerate as soon as a new release hits PyPI.

**Comment by shaded-enmity** [comment]
dotests

**Comment by ncoghlan** [comment]
Looking at https://github.com/kennethreitz/pipenv/commits/master the version we're going to need will be either 3.5.7 or 3.6.0 (the problem was fixed shortly after 3.5.6 was released, and there hasn't been a new release since then).

Since the fix has been merged upstream, that means the CI Ansible playbook could be updated to specify `'pipenv>3.5.6'` in this PR, and it should start passing once the release has been made.

**Comment by shaded-enmity** [comment]
Jenkins Test

**Pull request merged**
