### PR TITLE
Added missing changes for the integration tests

### PR DESCRIPTION
**Pull request by vinzenz**
Signed-off-by: Vinzenz Feenstra <vfeenstr@redhat.com>

### CODE REVIEW

**Comment by vinzenz** [comment]
Jenkins Test please
Jenkins: ok to test

**Comment by shaded-enmity** [comment]
Jenkins Test please

**Comment by vinzenz** [comment]
Jenkins Test please
Jenkins: ok to test

**Comment by ncoghlan** [comment]
Jenkins test

**Comment by vinzenz** [comment]
Abandon this for the virt-inspector path as a backup

**Pull request closed without merging**
