### PR TITLE
ugly way to expose ports for jbpms

### PR DESCRIPTION
**Pull request by mfranczy**

### CODE REVIEW

**Comment by mfranczy** [comment]
Jenkins Test please!

**Comment by mfranczy** [comment]
Jenkins: ok to test

**Comment by shaded-enmity** [comment]
Jenkins: ok to test

**Comment by shaded-enmity** [comment]
Jenkins Test

**Comment by shaded-enmity** [comment]
Testing on my box right now.

**Comment by shaded-enmity** [comment]
LGTM, merging (I've encountered some quirks in the drools initialization but I should be able to fix those in the init script)

**Pull request merged**
