### PR TITLE
Removal of trailing spaces in Python code

### PR DESCRIPTION
**Pull request by vinzenz**

### CODE REVIEW

**Comment by shaded-enmity** [comment]
Makes me wonder if we want to run `pep8` tool or something like that after/before `behave` tests.

**Comment by vinzenz** [comment]
I actually would go so far and go for flake8 checks - Maybe even using tox (as suggested by @mfranczy)
and we might want to consider unit tests as well

**Comment by vmindru** [comment]
+1 flake8

**Comment by vmindru** [comment]
yeah and +1 for tox, I have a positive experience using this within Ansible project integrates well with VIM.

**Pull request merged**
