### PR TITLE
Fixes #69 version reporting in leapp-tool

### LINKED ISSUE #69: fix version reporting of cli leapp-tool
version reporting does not seem to work 

```
[root@vmindru-test-03 ~]# /opt/leapp/bin/leapp-tool -v
usage: leapp-tool [-h] [-v]
                  {list-machines,migrate-machine,destroy-containers} ...
leapp-tool: error: too few arguments
[root@vmindru-test-03 ~]# 
```

### PR DESCRIPTION
**Pull request by vinzenz**
Signed-off-by: Vinzenz Feenstra <vfeenstr@redhat.com>

### CODE REVIEW

**Comment by vmindru** [comment]
+1

**Comment by vinzenz** [comment]
Rebased
Jenkins Test please

**Comment by shaded-enmity** [comment]
Jenkins Test

**Comment by shaded-enmity** [comment]
LGTM, merging 🎉

**Pull request merged**
