### PR TITLE
WIP: wip fixing mysql55 RHEL 6 issue

### PR DESCRIPTION
**Pull request by vmindru**
this fixes https://github.com/leapp-to/prototype/issues/79

### CODE REVIEW

**Comment by vmindru** [comment]
@vinzenz @shaded-enmity @ncoghlan - please review

**Comment by mfranczy** [comment]
Jenkins: ok to test

**Comment by vmindru** [comment]
try: Jenkins:  work B*&YCh!

**Comment by shaded-enmity** [comment]
Jenkins: ok to test

**Comment by shaded-enmity** [comment]
Jenkins Test

**Comment by vmindru** [comment]
rebased

**Comment by vmindru** [comment]
Jenkins Test

**Comment by vmindru** [comment]
@mfranczy  @shaded-enmity  @vinzenz @ncoghlan  need a +1 tessed passed ok.

**Comment by vinzenz** [comment]
LGTM +1

**Pull request merged**
